apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - chart: prometheus
        repoURL: https://prometheus-community.github.io/helm-charts
        version: "25.8.0"
        namespace: monitoring
      - chart: grafana
        repoURL: https://grafana.github.io/helm-charts
        version: "7.3.7"
        namespace: test
      - chart: sealed-secrets
        repoURL: https://charts.bitnami.com/bitnami
        version: "2.5.19"
        namespace: sealed-secrets
  template:
    metadata:
      name: '{{chart}}'
    spec:
      project: default
      sources:
      - repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          valueFiles:
          - $values/manifests/values/{{chart}}.yaml
      - repoURL: https://github.com/wmag19/homelab.git
        targetRevision: HEAD
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true