apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - chart: kube-prometheus-stack
            repoURL: https://prometheus-community.github.io/helm-charts
            version: 79.7.1
            namespace: monitoring
            releaseName: kube-prometheus-stack
          - chart: cloudnative-pg
            repoURL: https://cloudnative-pg.github.io/charts
            version: 0.27.1
            namespace: postgres
            releaseName: cnpg
          - chart: external-secrets
            repoURL: https://charts.external-secrets.io
            version: 2.2.0
            namespace: secrets
            releaseName: external-secrets
          - chart: metallb
            repoURL: https://metallb.github.io/metallb
            version: 0.16.1
            namespace: metallb-system
            releaseName: metallb
          - chart: gateway-helm
            repoURL: docker.io/envoyproxy
            version: v1.8.0
            namespace: envoy-gateway
            releaseName: envoy-gateway
          - chart: cert-manager
            repoURL: https://charts.jetstack.io
            version: v1.20.2
            namespace: cert-manager
            releaseName: cert-manager
  template:
    metadata:
      name: "{{chart}}"
    spec:
      project: default
      sources:
        - repoURL: "{{repoURL}}"
          chart: "{{chart}}"
          targetRevision: "{{version}}"
          helm:
            releaseName: "{{releaseName}}"
            valueFiles:
              - $values/manifests/values/{{chart}}.yaml
        - repoURL: https://github.com/wmag19/homelab.git
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: manifests
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/wmag19/homelab.git
        revision: HEAD
        directories:
          - path: manifests/*
          - path: manifests/values
            exclude: true
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/wmag19/homelab.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
