apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "9.3.2"
    helm:
      valueFiles:
      - $values/manifests/values/grafana.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test