apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
  namespace: miniflux
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault-store
    namespace: secrets

  target:
    name: miniflux
    creationPolicy: Owner

  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: miniflux-oauth2-client-id
      remoteRef:
        key: miniflux-oauth2-client-id
    - secretKey: miniflux-oauth2-client-secret
      remoteRef:
        key: miniflux-oauth2-client-secret
    - secretKey: miniflux-oauth2-redirect-url
      remoteRef:
        key: miniflux-oauth2-redirect-url
    - secretKey: miniflux-oauth2-discovery-endpoint
      remoteRef:
        key: miniflux-oauth2-discovery-endpoint
    - secretKey: miniflux-admin-password
      remoteRef:
        key: miniflux-admin-password
#miniflux-oauth2-redirect-url
