apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-postgres
  namespace: miniflux
spec:
  instances: 1
  bootstrap:
    initdb:
      database: miniflux2
      owner: miniflux
      secret:
        name: miniflux-postgres-secret

  storage:
    size: 1Gi