apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-navidrome-music
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  csi:
    driver: csi.san.synology.com
    volumeHandle: 67421b35-f13f-4f86-9498-262a6573429f
    volumeAttributes:
      baseDir: /volume1/pv-navidrome-music
      dsm: 192.168.1.136
      formatOptions: ""
      mountPermissions: "0770"
      protocol: smb
      source: //192.168.1.136/pv-navidrome-music
    nodeStageSecretRef:
      name: cifs-csi-credentials
      namespace: synology
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music-pvc
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: pv-navidrome-music
