apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-navidrome-music
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-navidrome-music
    namespace: navidrome
  csi:
    driver: csi.san.synology.com
    volumeAttributes:
      baseDir: /volume1/pv-navidrome-music
      dsm: 192.168.1.136
      formatOptions: ""
      mountPermissions: "0770"
      protocol: smb
      source: //192.168.1.136/pv-navidrome-music
    volumeHandle: 67421b35-f13f-4f86-9498-262a6573429f
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
