cronjob:
  schedule: "0 2 * * *"  # Run daily at 2 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

image:
  registry: ghcr.io
  repository: renovatebot/renovate
  tag: "41.76.0"

renovate:
  config: |
    {
      "platform": "github",
      "autodiscover": false,
      "repositories": ["wmag19/homelab"],
      "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
      "onboarding": false,
      "requireConfig": "optional",
      "argocd": {
        "fileMatch": ["\\.yaml$", "\\.yml$"]
      },
      "kubernetes": {
        "fileMatch": ["\\.yaml$", "\\.yml$"]
      },
      "helm-values": {
        "fileMatch": ["values\\.ya?ml$"]
      },
      "major": {
        "enabled": true
      },
      "logLevel": "debug"
    }

# Use existing secret for environment variables
existingSecret: renovate-secret

# Resource limits and requests
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000