# Use DaemonSet for better availability across nodes
deployment:
  kind: DaemonSet

# Disable IngressRoute dashboard (we'll use Gateway API)
ingressRoute:
  dashboard:
    enabled: false

# Enable Gateway API and other providers
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
  kubernetesGateway:
    enabled: true

# Enable experimental Gateway API features
experimental:
  kubernetesGateway:
    enabled: true

# Configure ports with HTTP->HTTPS redirect
# ports:
#   web:
#     redirectTo:
#       port: websecure
#   websecure:
#     tls:
#       enabled: true

# Use NodePort since no LoadBalancer available
service:
  type: NodePort

# Configure standard ports for Traefik
ports:
  web:
    port: 8000
  websecure:
    port: 8443

# Enable Gateway API resources to be created automatically
gateway:
  enabled: true
  listeners:
    web:
      port: 8000
      protocol: HTTP
      namespacePolicy:
        from: All

gatewayClass:
  enabled: true