apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault-store
  target:
    name: client-info-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          literal: |-
            client-info.yml: |
              clients:
              - host: {{ .host }}
                port: 5000
                https: false
                username: {{ .username }}
                password: {{ .password }}

  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: username
      remoteRef:
        key: synology-username
    - secretKey: password
      remoteRef:
        key: synology-password
    - secretKey: host
      remoteRef:
        key: synology-host
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smb-secret
  namespace: synology-csi
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault-store
  target:
    name: cifs-csi-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          literal: |-
            username: {{ .username }}
            password: {{ .password }}

  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: username
      remoteRef:
        key: synology-username
    - secretKey: password
      remoteRef:
        key: synology-password
