---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: synology-csi
spec:
  encryptedData:
    .dockerconfigjson: AgCYdwUcoAxdfqJVlGzuUQVOCRxL06b6J/HsIBaWumoTHW1DaToHOXB/rh5DSLV+y8M5paLSiKgao3jhNny5PeNUKpjhAN+Z88mMonsvRgPHM7WBwjuNHzcyhIZJu4vkc/w4GIK5PT6nKPyC3U5O18E/+td5jCNXLi4GT54wwO8IFJ1WycGR7w/8flxh5XnGGwtU2b+Ylf1N9xb8hXGlg4x9fcUeDEnOep26hg4vLqJ3G51Wum3YZqIZh63m7D7QOHeuDyg55FM1rAENW6Ed4YDpXQKPFFo2FqR+qluVlLCDd7j4fcry4P9ybVmbbQy2Ghbp1mijli4f+c4wS3mr91g9fqd0DGnLsarecaF+wpAzmAHyKECXRYLZkMcq/+HFMdM0+fdVrFn4HKkXBwS/4YZ1jTGVfaAyIWM0TqaS20qLX9IJb62Wh/fRrDAaDskJKcQ4x+4tmevXf1qAZzzekEig8hPzX28Vx1fyrqsY6Okmn30fv4WZQ9Qr7Y07DlrK5FBGYOzqzay33Jis3BO7Lb30qMhDHfFbUPN+1X4ldEnO8XiYxivD8zBAYYrGO6zdYqN9caAZAi++ZFpK5UeFSLiDw6h3vaa3biEnw4MXIPJQ99jicuor4ldnc/pofMswT/tstnZtq4WMCP9ZKCups07fGTC7ZmnPE6x08ljtdLLlCbxPnGKCbBGOwCnDLKLQzwFGTxWLeWDtyg90nK/ovJVkkbUesodPj6mxMV9JNwi8sr2JZKsOOLRdlCQpuXMy7x7Ue4xGebdiKcqGZ8Y+0Klq7CGIMdLs7YR0La1hnV5PVEEiG34hkw2+J53+g7WcUMJasr2E3hiWn5kljXxZoQRP+WkN/xawSKhDtIdWz5zbx+jv+gz0fFuHrPpI6GbZd0XIxaUko6AOyhgV/ATeHoZt/xl3T3W9JQDtTOhs5SttZi7/COH1ibQsZHn2ZlTDQXF9rVMi/g15Vj4O4Ux1lrZp/LOHFGGMvzvTl6I=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: synology-csi
    type: kubernetes.io/dockerconfigjson
