---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgAkmyLsfWS0C1MUWom9eW1gVcxX5crK+py/Jl0Ho2aieO/c4mbSDAm/lB8mHkEXgJVUFobcLbxgxuH9O8LlUqrblmnWz1uBfuqOff33cEiKPKWVnVIMghIbhFWTeKkZh1uRg0GUoa0RVCAVrCnSHthttkl9+S9WZWD/Duhx+g6KSeQvLWxaoIUTcqNSE/fzVAbL60YN1N0+Tgcx6a7q9DINN9mc8Gjy0SGljunl40VtTq9cpbpKOxOH8jvFVzdOUp2eUt6V0WnvVLKhydWzR4wZhoQ4OWDbLOnvlnK3jcNfbpg+rS3Bpb6Ry6vz5b/AQVXnt/h3JDKIiALoURDrmTXgdR3BPktUCE53Aolmv+x0ctkoYPFtX2hoOqiYZpNDGb4PGyv9RAte6QTLQBIaL3sil0/Q/TxBU+qs+81inL2MKM5zM3FeqNgN/i5fZ9OK4C7Ajj3JHXFAGB+DUBPXOOKKTPIj9kezsAtT4K2rTkDzHla/PB1I/fHKsGwdrDef2888MAc+F1nZRcAtUR0Qi0h2ljfc/jxhLZjAQn0nmwyutKPAWCrFBGPLsHgKaVnRWiyBUpP5Qu/YxZGLZnrdVBnXyADgjXF1KvWc2RqMHaLdmioEKCGvPVnKZ85mmVxxX65VsM44UO0vvPHQ/7Ay+v7hyocTM9hsfEmlnJRm2QT4jCozPwMOar67R/gECMizlkaS4kqy5yFSFuOnHvagIuQDlDtWD3GOY9jupv8yAjkzhmNMP1Xo3scepS6LFdYGamjQdBq5wBbVuoxK5PI/U8/zUXkgmdyN84xvNrlCirpyVjjdfauzgDHQfU8vBhqO6kx6x2sO7iYx24S7C5C6hztUsMjNaWUx0at0zmbJPN3ZgGOuz1YvY9QYzLOwO1V6zVw69jgEiOu42CLzsyyeSwqiYu5KEWLk+4yCDr2zr9OnwsKGq2xX5MA0mlFdd+GtVBrMLZFSQuJTKxB62aQfhE7A8Afk0CeU9SNZuct5GEGyB+FsE6cU9u3XX/0LqtONJAuVi3jW3wJvUShdXTI6gM3EiMyf0ZpEgaZG+t+RbOsSaLP+XP9rcKKXEXSD7bYf1Y5M9HWRMKRNR95L1MvQxJXmjkSSlTo=
  template:
    metadata:
      name: client-info-secret
      namespace: synology-csi
