apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-retain
provisioner: csi.san.synology.com
parameters:
  protocol: "nfs"
  dsm: "192.168.1.136"
  location: "/volume1"
  mountPermissions: "0755"
mountOptions:
  - nfsvers=4.1
reclaimPolicy: Retain
allowVolumeExpansion: true
